### ISSUE TITLE
Min and max , value property not support decimal value

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [fabricelacharme/ColorSlider#4]
Hi @fabricelacharme 
it is support decimal datatype in minimum maximum and vaue property
i need choose for decimal value -0.5 to +5.0 it is not possible in here else i don't know   

Thank for support

**Comment by fabricelacharme** [comment]
Hello,
yes, normal, maximum and maximum are declared as "int" in the code.
I have to check.
Thanks for your feedback

**Comment by fabricelacharme** [comment]
Hello the new version 1.0.0.3 support now decimal datatype in minimum and maximum value property.

**Comment by rajesh-smartwebtech** [comment]
Thank you
